[package]
name = "metaheurstics"
version = "0.1.1"
edition = "2024"

[dependencies]
csv = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
rand = "0.10.0-rc.5"
eframe = "0.33.0"
egui = "0.33.0"
